var channels_name='IndoPopChannel', //example
channels_title='jQuery plugin by @bachors',
apikey='YOUR GOOGLE API KEY';

eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$.C({q:\'D://r.E.s/t/F/12?G=H&13=\'+I+\'&J=\'+K,14:15,L:\'M\'}).N(4(a){6 b=a.7[0].H.16.17,O=a.7[0].18,P=\'\';m(b,K,P,19,O,I)});4 m(f,g,h,j,k,l){$.C({q:\'D://r.E.s/t/F/1a?G=9&1b=\'+f+\'&J=\'+g+\'&1c=\'+h,L:\'M\'}).N(4(c){6 d=\'\';d+=\'<3 2="1-8-1d"><5 2="1-1e-n">\'+j+\'</5><Q><5 2="1-8-o">o <a 1f="1g://r.t.s/1h/\'+l+\'" 1i="1j">\'+l+\'</a></5><1k>\';d+=\'<i 2="p p-R-1l S" n="1m T"></i> \';d+=\'<i 2="p p-R-1n U" n="1o T"></i></3><3 2="1-8-1p">\';$.V(c.7,4(i,a){6 b=c.7[i].9.1q.1r;1s(b);d+=\'<3 2="1-u" v-w="\'+b+\'"><3 2="1t"><1u 1v="\'+c.7[i].9.1w.1x.q+\'"><5 2="1-8-1y"></5></3>\';d+=c.7[i].9.n+\'<Q>\';d+=\'<5 2="1-8-o">o \'+c.7[i].9.1z+\'</5></3>\'});d+=\'</3>\';$(\'.1A\').W(d);X(c.x==Y){6 e=$(".1-u").Z("v-w");10(e,k,l)}X(c.x!=Y){$(\'.S\').y(4(){6 a=c.x;m(f,g,a,j,k,l);z A})}$(\'.U\').y(4(){6 a=c.1B;m(f,g,a,j,k,l);z A});$(".1-u").V(4(){$(B).y(4(){6 a=$(B).Z("v-w");$("W, 1C").1D({1E:0},1F);$(\'3\').1G(\'1-8-11\');$(B).1H(\'1-8-11\');10(a,k,l);z A})})})}',62,106,'|ibacordotcom|class|div|function|span|var|items|vid|snippet|||||||||||||youtube_video_list|title|by|fa|url|www|com|youtube|play|data|vvv|prevPageToken|click|return|false|this|ajax|https|googleapis|v3|part|contentDetails|channels_name|key|apikey|dataType|json|done|chid|nekpag|br|fast|ibacordotcom_vid_prev|videos|ibacordotcom_vid_next|each|html|if|null|attr|youtube_det|active|channels|forUsername|crossDomain|true|relatedPlaylists|uploads|id|channels_title|playlistItems|playlistId|pageToken|top|nav|href|http|user|target|_BLANK|hr|backward|Previous|forward|Next|bottom|resourceId|videoId|getwaktu|ibacordotcom_youtube_thumb|img|src|thumbnails|default|tm|channelTitle|ibacordotcom_youtube_channels|nextPageToken|body|animate|scrollTop|500|removeClass|addClass'.split('|'),0,{}))
function youtube_det(vvv,chid,channels_name) {
	$.ajax({
		url: 'http://gdata.youtube.com/feeds/api/videos/' + vvv + '?v=2&alt=jsonc',
		dataType: 'json'
	}).done(function (data) {
		var html = '';
		html += '<iframe src="http://www.youtube.com/embed/' +vvv+ '" allowfullscreen="" frameborder="0" class="ibacordotcom-vid-iframe"></iframe>';
		html += '<div class="ibacordotcom-vid-box"><h1>' + data.data.title + '</h1>';
		html += '<div class="ibacordotcom-vid-box-user"><a href="http://www.youtube.com/channel/' + chid + '" target="_BLANK"><span id="ibacordotcom-user-img"></span> <span class="ibacordotcom-uploader">' + data.data.uploader + '</span></a><i class="fa pull-right fa-2x"> ' + data.data.viewCount.toLocaleString() + 'x</i></div><hr>Share <input type="text" value="http://youtu.be/' + vvv + '" class="ibacordotcom-input" onclick="this.focus();this.select()" readonly="readonly"><i class="fa fa-thumbs-up pull-right"> <span>' + data.data.likeCount.toLocaleString() + '</span></i></div>';
		html += '<div class="ibacordotcom-vid-box"><i class="fa fa-clock-o"> <span>' + _timeSince(new Date(data.data.uploaded).getTime()) + '</span></i><a href="http://www.youtube.com/' + data.data.category + '" target="_BLANK"><i class="fa fa-tags pull-right"> <span>' + data.data.category + '</span></i></a><hr>' + urlify(data.data.description).replace(/\n/g, '<br>') + '<br></div>';
		gplus (channels_name)
		$('.ibacordotcom_vid_play').html(html);
	});
}
eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('1 6(c){$.7({8:\'9://d.e.f/g/h/i/\'+c+\'?v=2&j=k\',l:\'m\'}).n(1(a){o b=a.p.q,0=r.s(b/3),4=b-0*3,5=0+\':\'+4;$(\'.t-u-w\').x(5)})}',34,34,'minutes|function||60|seconds|waktu|getwaktu|ajax|url|http||||gdata|youtube|com|feeds|api|videos|alt|jsonc|dataType|json|done|var|data|duration|Math|floor|ibacordotcom|vid||tm|html'.split('|'),0,{}))
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('6 o(b){8 c=/(h?:\\/\\/[^\\s]+)/g;2 b.p(c,6(a){2\'<a q="\'+a+\'" r="t" u="v">\'+a+\'</a>\'})}6 w(c){8 d=\'h://x.y.z/A/B/C/\',j=\'/D/E\',e=\'k(l(m(f)))\';$.F({f:d+\'+\'+c+j+\'?G=H&e=\'+e+\'&I=1\',J:K,L:\'M\'}).N(6(a){8 b=a.k,i=0,9=\'\';O(i=0;i<b.P;i+=1){9+=\'<n Q="\'+b[i].l.m.f+\'" R="" />\'}$(\'#S-T-n\').9(9)})}6 U(a){8 s=3.4((V W()-a)/X),i=3.4(s/Y);7(i>1){2 i+" Z 5"}i=3.4(s/10);7(i>1){2 i+" 11 5"}i=3.4(s/12);7(i>1){2 i+" 13 5"}i=3.4(s/14);7(i>1){2 i+" 15 5"}i=3.4(s/16);7(i>1){2 i+" 17 5"}2 3.4(s)+" 18 5"}',62,71,'||return|Math|floor|ago|function|if|var|html|||||fields|url||https||apiend|items|actor|image|img|urlify|replace|href|rel||nofollow|target|_BLANK|gplus|www|googleapis|com|plus|v1|people|activities|public|ajax|key|AIzaSyCj2GrDSBy6ISeGg3aWUM4mn3izlA1wgt0|maxResults|crossDomain|true|dataType|jsonp|done|for|length|src|alt|ibacordotcom|user|_timeSince|new|Date|1000|31536000|years|2592000|months|86400|days|3600|hours|60|minutes|seconds'.split('|'),0,{}))
